/**
 * Caching System Architecture Stub
 * 
 * Future caching strategy for NPM packages:
 * 
 * 1. Global Cache (`.cache/packages`):
 *    - Stores downloaded NPM packages locally to avoid redownloads.
 *    - Structured by package name and version (e.g., `.cache/packages/lodash/4.17.21`).
 * 
 * 2. Bundle Cache (`.cache/bundles`):
 *    - Stores pre-bundled outputs generated by esbuild.
 *    - When AST detects an import like `import _ from "lodash"`, 
 *      the system checks the bundle cache for `lodash.bundle.js`.
 *    - If missing, it invokes the installer -> resolver -> esbuild -> writes to cache.
 */

export interface CacheProvider {
  hasPackage(pkg: string, version: string): Promise<boolean>;
  getPackage(pkg: string, version: string): Promise<string | null>;
  setPackage(pkg: string, version: string, path: string): Promise<void>;
  
  hasBundle(pkg: string): Promise<boolean>;
  getBundlePath(pkg: string): Promise<string | null>;
  setBundlePath(pkg: string, path: string): Promise<void>;
}
